server:
    port: ${PORT:8000}

spring:
    application:
        name: cashin-ms   
    kafka:
        bootstrap-servers: ${KAFKA_HOST:localhost:9092}

    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost:3306}/cashin-ms?createDatabaseIfNotExist=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver